   
   ############################################################
   ##                                                        ##
   ##                    WAKE ON LINE                        ##
   ##                                                        ##
   ############################################################

- platform: wake_on_lan
  mac: !secret mac_pc
  host: !secret ip_pc
  turn_off:
      service: hassio.addon_stdin
      data:
          addon: core_rpc_shutdown
          input: roman-pc
   
