 
   ############################################################
   ##                                                        ##
   ##                    WEATHER TRACK                       ##
   ##                                                        ##
   ############################################################
   

- platform: darksky
  mode: daily
  api_key: !secret dark_sky_key